### ISSUE TITLE
OSX hiccups

### ISSUE THREAD

**Issue by dirkraft** [rholder/debinate#10]
Should either provide instructions, or get fancy and detect and prefer some of these non-BSD alternatives.

I had to 
```
ln -s /usr/local/bin/gfind /usr/local/bin/find
ln -s /usr/local/bin/gxargs /usr/local/bin/xargs
```
which makes sense for me because my /usr/local/bin is before /usr/bin (where BSD commands live)
```
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:... #and so on
```

md5/md5sum may also be problematic but I already linked both command names in the past for reasons.

For completeness, the g* utils come from `brew install coreutils`

**Comment by rholder** [comment]
As of `0.4.0`, it should be possible to run `debinate` on OSX after a `brew install coreutils findutils gnu-tar`. However, if the project has Python dependencies that are compiled, they'll only work on OSX. This support was mostly added to handle the new `debinate generate` functionality.
